### DISCUSSION TITLE
Is it possible to import tasks configurations from other files in scheduler.yaml

### DISCUSSION THREAD

**Discussion by MarcelWilhelmi** [Guikingone/SchedulerBundle#55] [Q&A]
Hey,

Is there a way to import files within the scheduler.yaml?
I'd like to extract some task configurations into separate files and import those within the scheduler.yaml, somehow like this:

```yaml
scheduler_bundle:
    transport:
        dsn: '...'
    tasks:
        my-first-task:
            type: 'command'
            command: '...'
        import:
            my_tasks_1.yaml
            my_tasks_2.yaml
```

Is this possible?

I tried using imports [https://symfony.com/doc/current/service_container/import.html](https://symfony.com/doc/current/service_container/import.html) but couldn't get this working.

Kind regards,
Marcel

**Comment by Guikingone** [comment]
Hi @MarcelWilhelmi 👋🏻 

For now, it's not possible but the suggestion can be an interesting feature, I'm not sure about the syntax: 

```yaml
scheduler_bundle:
    transport:
        dsn: '...'
    tasks:
        my-first-task:
            type: 'command'
            command: '...'
        import:
            my_tasks_1.yaml
            my_tasks_2.yaml
```

This seems weird as the `import` key can be the one used to create a new task, maybe we could use it but add it as a special meaning in the configuration (thanks to normalization). 

Regarding the import key from the DIC, the behaviour is normal as it's a special key used in the DIC configuration 🙂
