### DISCUSSION TITLE
is it possible to force consume a task list ?

### DISCUSSION THREAD

**Discussion by jvancoillie** [Guikingone/SchedulerBundle#60] [Q&A]
Let me explain, I have a task list configured to be executed each month `0 0 1 * *` (is the @monthly expression available ?) see below 
```yaml
# config/packages/scheduler.yaml
scheduler_bundle:
    transport:
        dsn: 'doctrine://default?execution_mode=first_in_first_out&table_name=scheduler_tasks&auto_setup=false'
    tasks:
        activation:
            type: 'command'
            command: 'app:activation'
            description: 'activate params'
            single_run: true
            output: true
            output_to_store: true
            priority: 1
            tags: ['api']
        etablissements:
            type: 'command'
            command: 'app:etablissements'
            expression: '0 0 1 * *'
            description: 'Import des établissements'
            output: true
            tags: ['api']
        communes:
            type: 'command'
            command: 'app:communes'
            expression: '0 0 1 * *'
            description: 'Import des communes'
            output: true
            tags: ['api']
```

and I would need that at the first execution of the `scheduler:consume` for example a deployment on the 15th of the month that the tasks are automaticaly executed. 

do I have to switch to a `single_run` configuration like this 
```yaml
# config/packages/scheduler.yaml
scheduler_bundle:
    transport:
        dsn: 'doctrine://default?execution_mode=first_in_first_out&table_name=scheduler_tasks&auto_setup=false'
    tasks:
        deploy:
            type: 'chained'
            single_run: true
            tasks:
                activation:
                    type: 'command'
                    command: 'app:activation'
                    description: 'activate params'
                    output: true
                    output_to_store: true
                    priority: 1
                etablissements_single_run:
                    type: 'command'
                    command: 'app:etablissements'
                    single_run: true
                    description: 'Import des établissements'
                    output: true
                    tags: ['api']
                communes_single_run:
                    type: 'command'
                    command: 'app:communes'
                    description: 'Import des communes'
                    output: true
                    tags: ['api']
        etablissements:
            type: 'command'
            command: 'app:etablissements'
            expression: '0 0 1 * *'
            description: 'Import des établissements'
            output: true
            tags: ['api']
        communes:
            type: 'command'
            command: 'app:communes'
            expression: '0 0 1 * *'
            description: 'Import des communes'
            output: true
            tags: ['api']
```
