### DISCUSSION TITLE
Chainedtask order

### DISCUSSION THREAD

**Discussion by jvancoillie** [Guikingone/SchedulerBundle#69] [Q&A]
How does the scheduling of a [chainedtask](https://github.com/Guikingone/SchedulerBundle/blob/main/doc/tasks.md#chainedtask) work ? 
According to the order defined in the yaml configuration ? 
Can we use the priority configuration entry to order the chained tasks ?

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

That's an ... **_interesting_** point that you're mentioning here 😄 

At the beginning of the development of this bundle, the feature was present then ... I remove it for some random reasons, by default, tasks are executed in the order defined in the configuration file (no matter the format). 

We can sort the tasks using `priority` but the feature is not available for now, maybe you want to contribute on it? 🙂

**Reply by jvancoillie** [reply]
Of course, I volunteer to contribute. I'm afraid I won't be up to the task, but I want to give it a try. I'll see what I can do on my end about this. It is a good exercise to better understand the functioning and the philosophy of this bundle.

**Comment by jvancoillie** [comment]
Hi @Guikingone, 

I have just set up an environment to study the bundle and see how we could deal with the notion of priority.

I realize that the order of the configuration of the task is not that which one finds at the execution, therefore it seems important to me to introduce the notion of priority. 

my yaml configuration : 
```yaml
scheduler_bundle:
  transport:
#    dsn: 'filesystem://first_in_first_out'
    dsn: 'doctrine://default?execution_mode=first_in_first_out'
  tasks:
    world:
      type: 'command'
      command: 'app:world'
      expression: '* * * * *'
      description: 'world command'
    hello:
      type: 'command'
      command: 'app:hello'
      expression: '* * * * *'
      description: 'hello command'
```
 the `bin/console scheduler:list`
 <img width="1132" alt="Capture d’écran 2021-04-27 à 09 16 27" src="https://user-images.githubusercontent.com/21243943/116200983-4bb41680-a739-11eb-8ffe-b4c85ded2bbb.png">

the `bin/console scheduler:consume`
<img width="1132" alt="Capture d’écran 2021-04-27 à 09 17 28" src="https://user-images.githubusercontent.com/21243943/116201083-69817b80-a739-11eb-843d-cdc724c5aa90.png">

we can see that the order of execution is not the same as the configuration. in both transports `filesystem` and `doctrine`.

How do you see priority management ?
do we need to add a priority policy ?
