### DISCUSSION TITLE
ChainedType vs SimpleTask

### DISCUSSION THREAD

**Discussion by jvancoillie** [Guikingone/SchedulerBundle#87] [Q&A] [answered]
What is the advantage of using a chained task rather than a simple task list ? 

For example:

```yaml
    // chained type
    tasks:
      chained:
        type: 'chained'
        single_run: true
        description: 'chained tasks'
        output: true
        output_to_store: true
        tasks:
          command1:
            type: 'command'
            command: 'app:command1'
          command2:
            type: 'command'
            command: 'app:command2'
          command3:
            type: 'command'
            command: 'app:command3'
          command4:
            type: 'command'
            command: 'app:command4'
```
VS

```yaml
    // simple FiFO tasks
    tasks:
      command1:
          type: 'command'
          command: 'app:command1'
          single_run: true
      command2:
          type: 'command'
          command: 'app:command2'
          single_run: true
      command3:
          type: 'command'
          command: 'app:command3'
          single_run: true
      command4:
          type: 'command'
          command: 'app:command4'
          single_run: true
```
This configuration has the advantage of giving information task by task, which is not found on a chained task. 
Moreover when we list the tasks `bin/console scheduler:list` we don't find the detail of the embedded tasks how to know if one of the subtask is failed and the execution time of each of them 🤔
