### ISSUE TITLE
DueTask scheduled inconsistent 	

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#105]
There is a problem with the recovery and execution of scheduled tasks. 

task configuration : 
```yaml
scheduler_bundle:
  transport:
    dsn: 'doctrine://default?execution_mode=first_in_first_out'
  tasks:
    bar:
      type: 'command'
      command: 'debug:router'
      description: 'Display current routes for an application'
```
See below
<img width="1452" alt="Capture d’écran 2021-05-09 à 13 20 13" src="https://user-images.githubusercontent.com/21243943/117570279-b82ffd80-b0c9-11eb-9d77-f96952aa9ade.png">

when setting up the tasks we can see that the next execution is set `2021-05-09T11:19:00+00:00`

I then request a consume, the task is executed and the date of last execution `2021-05-09T11:18:39+00:00` is less than the initial date of execution!
