### ISSUE TITLE
ChainedTask no longer works

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#125]
the execution of the subtasks no longer works.

with the following configuration, only the `bar` task seems to run.

```yaml
scheduler_bundle:
  transport:
    dsn: 'doctrine://default?execution_mode=first_in_first_out'
  tasks:
    chained:
      type: 'chained'
      output: true
      description: 'chained with 2 tasks'
      tasks:
        foo:
          type: 'command'
          command: 'app:foo'
          description: 'command foo chained'
          output: true
        bar:
          type: 'command'
          command: 'app:bar'
          description: 'command bar in chained'
          output: true
    task5:
      type: 'command'
      command: 'app:foo'
      description: 'command task 5'
      output: false
    task6:
      type: 'command'
      command: 'app:bar'
      description: 'command task 6'
      output: false
```

<img width="846" alt="Capture d’écran 2021-05-22 à 18 20 59" src="https://user-images.githubusercontent.com/21243943/119233698-89367480-bb2a-11eb-9911-0e323f77085d.png">
