### ISSUE TITLE
feat(pool): allow to specify an application name

### ISSUE THREAD

**Issue by Guikingone** [Guikingone/SchedulerBundle#181]
# Context

Allow to specify an "application name" that can be used to distinguish applications when used in a pool context

# Implementation

```yaml
scheduler_bundle:
    name: 'foo'

# ...
```
