### ISSUE TITLE
Messenger example with custom command and transport

### ISSUE THREAD

**Issue by ToshY** [Guikingone/SchedulerBundle#199]
I'm fairly new to Messenger and I'm encountering some minor inconveniences due to not fully understanding on how to use this bundle. I see a section about [Messenger](https://github.com/Guikingone/SchedulerBundle/blob/main/doc/messenger.md) but also about [MessengerTasks](https://github.com/Guikingone/SchedulerBundle/blob/main/doc/tasks.md#messengertask), but it's still confusing on how to use these if I just want to use some custom console commands and existing transports.

Let me just start with that I finally got a working example with the following config, command, message and handler, which throws an exception with custom text:

`scheduler.yaml`
```yaml
scheduler_bundle:
    timezone: UTC
    transport:
        dsn: 'cache://app'

    tasks:
        app-hello:
            type: 'command'
            command: app:schedule:hello'
            expression: '*/2 * * * *'
            description: 'Hello world exception schedule'
```
`messenger.yaml`
```yaml
framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - App\Message\Middleware\AuditMiddleware

            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Message\Middleware\AuditMiddleware

            query.bus: ~

        failure_transport: failed

        transports:
            failed:
                dsn: 'doctrine://default?queue_name=failed'

            failed_cron:
                dsn: 'doctrine://default?queue_name=failed_cron'

            cron:
                dsn: 'amqp://...'
                failure_transport: failed_cron
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: cron
                    queues:
                        messages_cron:
                            binding_keys: [ cron ]

        routing:
            # Route your messages to the transports
            'App\Message\HelloWorldException': cron

```
`App\Command\HelloWorldExceptionCommand.php`
```php
/**
 * Class HelloWorldExceptionCommand
 */
final class HelloWorldExceptionCommand extends Command
{
    /** @var string */
    protected static $defaultName = 'app:schedule:hello';

    /** @var string */
    protected static $defaultDescription = 'Creates hello world exception.';

    private MessageBusInterface $messageBus;

    /**
     * HelloWorldExceptionCommand constructor.
     * @param MessageBusInterface $messageBus
     */
    public function __construct(MessageBusInterface $messageBus)
    {
        parent::__construct();
        $this->messageBus = $messageBus;
    }

    protected function configure()
    {
        $this->setDescription(self::$defaultDescription)
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $this->messageBus->dispatch(new HelloWorldException('HELLO WORLD'));

        return Command::SUCCESS;
    }
}
```

`App\Message\HelloWorldException.php`
```php
namespace App\Message;

/**
 * Class HelloWorldException
 */
final class HelloWorldException
{
    private string $test;

    /**
     * HelloWorldException constructor.
     * @param string $test
     */
    public function __construct(
        string $test
    ) {
        $this->test = $test;
    }

    /**
     * @return string
     */
    public function getTest(): string
    {
        return $this->test;
    }
}
```
`App\Message\Handler\HelloWorldExceptionHandler.php`
```php
namespace App\Message\Handler;

use Exception;
use App\Message\HelloWorldException;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;

/**
 * Class HelloWorldExceptionHandler 
 */
final class HelloWorldExceptionHandler implements MessageHandlerInterface
{

    /**
     * @param HelloWorldException $helloWorldException
     * @throws Exception
     */
    public function __invoke(HelloWorldException $helloWorldException): void
    {
        throw new Exception(
            sprintf(
                'Something went wrong, this message `%s` needs to be in failed_cron transport',
                $helloWorldException->getTest()
            )
        );
    }
}
```

And when executing `messenger:failed:show`, it shows the correct exception in the `cron` transport

```
Failed Message Details
======================

 ------------- ----------------------------------------------------------------------------------
  Class         App\Message\HelloWorldException
  Message Id    ---
  Failed at     ---
  Error         Something went wrong, this message `HELLO WORLD` needs to be in failed_cron transport
  Error Code    0
  Error Class   Exception
  Transport     cron
 ------------- ----------------------------------------------------------------------------------
```

The problem is that I have the feeling I'm just making it harder for myself by not using `MessageTask` (or dispatching with `TaskToExecuteMessage`), but I just can't figure out on how to use it. Could someone elaborate on how to simplify this example?

---
```
Symfony (Messenger): 5.3.9
SchedulerBundle: 0.7.1
