### ISSUE TITLE
MessengerTask not working

### ISSUE THREAD

**Issue by jogoool** [Guikingone/SchedulerBundle#218]
I just create a fresh Symfony project to test the bundle, I followed the documentation. the configured tasks are working fine but when I try to create MessengerTask it is not listed on the task list ` bin/console scheduler:list `.

| Q                | A
| ---------------- | ---
| PHP version?     | 7.4
| Bundle version?  | 0.7.1
| Symfony version? | 5.4

```yaml
scheduler_bundle:
    transport:
        dsn: 'filesystem://first_in_first_out'
    tasks:
        foo:
            type: 'command'
            command: 'debug:route'
            expression: '*/5 * * * *'
            description: 'A simple cache clear task'
            options:
                env: test
```

messenger config

``` yaml
framework:
    messenger:
        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
             'App\Message\Command\LogMessage': async
```

```php
namespace App\Task;

use App\Message\Command\LogMessage;
use SchedulerBundle\SchedulerInterface;
use SchedulerBundle\Task\MessengerTask;

class LoggerTask
{
    public function __invoke(SchedulerInterface $scheduler) {
        $task = (new MessengerTask('log-message', new LogMessage('log message')))
            ->setExpression('*/5 * * * *');
        $scheduler->schedule($task);
    }
}
```

output of  ` bin/console scheduler:list `.

```sql
+-------------+------+---------------------------+-------------+---------------------+---------------------------+-------------------------+-----------------------------+---------+------+
| Type        | Name | Description               | Expression  | Last execution date | Next execution date       | Last execution duration | Last execution memory usage | State   | Tags |
+-------------+------+---------------------------+-------------+---------------------+---------------------------+-------------------------+-----------------------------+---------+------+
| CommandTask | foo  | A simple cache clear task | */5 * * * * | Not executed        | 2021-12-23T19:40:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
+-------------+------+---------------------------+-------------+---------------------+---------------------------+-------------------------+-----------------------------+---------+------+
```
