### ISSUE TITLE
Docrine transport might not work properly with Postresql

### ISSUE THREAD

**Issue by db306** [Guikingone/SchedulerBundle#229]
The following configuration works for MySQL (8.0) but not when using Postgresql (11.5) 

```yaml
scheduler_bundle:
    transport:
        dsn: 'doctrine://default?execution_mode=first_in_first_out'
```

When using Postgresql this output the following error when rebooting:

```
SQLSTATE[0A000]: Feature not supported: 7 ERROR:  FOR SHARE is not allowed with aggregate functions
```

We can close this ticket if others have managed to make this work on Postgres

Thanks
