### ISSUE TITLE
bug(bridge): Rebooting the scheduler clears everything in the transport

### ISSUE THREAD

**Issue by xaviermarchegay** [Guikingone/SchedulerBundle#234]
I use Redis as a transport for the scheduler. I also use Redis as the cache storage to store info like youtube/spotify oauth tokens.

When I have to reboot the scheduler, it clears everything in Redis.

https://github.com/Guikingone/SchedulerBundle/blob/059c74276e2616625ec4db1e1142c599cf034cdd/src/Scheduler.php#L270

Do you think that it would be possible for the scheduler to only clear the tasks?

Thanks

**Comment by Guikingone** [comment]
Hi @xaviermarchegay 👋🏻 

Could you provide the scheduler dsn?

Here's the current implementation: 

```php

    /**
     * {@inheritdoc}
     */
    public function empty(): void
    {
        $keys = $this->connection->hKeys($this->list);
        if ([] === $keys) {
            return;
        }

        if (!$this->connection->hDel($this->list, ...$keys)) {
            throw new TransportException('The list cannot be emptied');
        }
    }
```

You can configure the list if desired.

**Comment by xaviermarchegay** [comment]
In scheduler.yaml

```
    transport:
        dsn: 'cache://app'
```

In cache.yaml
```
framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        app: cache.adapter.redis
```

I am guessing that the scheduler dsn is wrong?
