### ISSUE TITLE
bug(bridge): postgres not working

### ISSUE THREAD

**Issue by dobbidev** [Guikingone/SchedulerBundle#272]
Q | A
-- | --
PHP version? | 8.1
Bundle version? | 0.9.3
Symfony version? | 6.0
doctrine/dbal version? | 3.3.6

Hello,

after installing your bundle and creating the first Task in scheduler.yaml:
```
scheduler_bundle:
  transport:
    dsn: 'doctrine://default?execution_mode=first_in_first_out&table_name=scheduler_tasks&auto_setup=true' # Or 'dbal://default?execution_mode=first_in_first_out'
  tasks:
    foo:
      type: 'command'
      command: 'cache:clear'
      expression: '*/5 * * * *'
      description: 'A simple cache clear task'

```

I get the following error:
```
SchedulerBundle\Exception\
TransportException
Invalid column index
```

After long debugging I found the following part, which makes the problem:
https://github.com/Guikingone/SchedulerBundle/blob/a8335cb72e8de96f33512ef352465d622bbd1cb5/src/Bridge/Doctrine/Transport/Connection.php#L162 

The fetchOne function throws this error, without this 3 Lines (162-164) the table get the data inserted.

Is this a known Issue?
Or can I workaround this exception in any way?

Thx

Dobbi
