### ISSUE TITLE
bug(scheduler): regression on scheduler:reboot (0.9.4)

### ISSUE THREAD

**Issue by xaviermarchegay** [Guikingone/SchedulerBundle#297]
With 0.9.3 : 

![image](https://user-images.githubusercontent.com/658523/184326310-4ffdc8d0-e1fe-47ae-baaf-3fa93fbeba78.png)

I upgrade the SchedulerBundle : 
![image](https://user-images.githubusercontent.com/658523/184326457-d736c12b-cb84-459c-acc3-2809b532ffb4.png)

With 0.9.4 : 

![image](https://user-images.githubusercontent.com/658523/184326359-036a2ea5-386a-436a-8c9b-8cd0c30c0c40.png)

Content of the scheduler.yaml

```yaml
scheduler_bundle:
    scheduler:
        mode: 'lazy'
    probe:
        enabled: true
        path: '/_probe'
    transport:
        dsn: 'doctrine://default?execution_mode=first_in_first_out'
    tasks:
        schedule_job:
            type: 'command'
            command: 'piconerd:scheduler'
            expression: '0 0 * * *'
            description: 'Scheduler'

```
