### ISSUE TITLE
Too few arguments to function SchedulerBundle\Transport\FailOverTransportFactory::__construct()

### ISSUE THREAD

**Issue by MarcelWilhelmi** [Guikingone/SchedulerBundle#33]
Hello,

when using failover or doctrine/dbal as transport dsn the following error is thrown:
`Too few arguments to function SchedulerBundle\Transport\FailOverTransportFactory::__construct(), 0 passed in [...]/var/cache/dev/ContainerXePqEvI/App_KernelDevDebugContainer.php on line 1071 and exactly 1 expected`

Example scheduler.yaml:
```
scheduler_bundle:
    transport:
        dsn: 'failover://(filesystem://first_in_first_out || memory://first_in_first_out)'
    tasks:
        foo:
            type: 'command'
            command: 'cache:clear'
            expression: '*/5 * * * *'
            description: 'A simple cache clear task'
```

I'm using guikingone/scheduler-bundle 0.3.1, PHP 7.4 and Symfony 5.2.4.

Is this a known error or am I doing something wrong?

Kind regards,
Marcel
