### ISSUE TITLE
bug(sort): BatchPolicy

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#79]
what is this array_walk for ?

https://github.com/Guikingone/SchedulerBundle/blob/0efd88bdd39c04dda6f9f821465f70f1305ea15a/src/SchedulePolicy/BatchPolicy.php#L21-L24

Think there is an issue ...
what happens if we set a `priority` to -1000
it will not pass the validation during the `setPriorty(--$priority)` !

**Comment by Guikingone** [comment]
The array_walk act as a simple look, the idea is to adapt the priority to be less and less important for each tasks: 

Source: https://man7.org/linux/man-pages/man7/sched.7.html

```txt
   SCHED_BATCH: Scheduling batch processes
       (Since Linux 2.6.16.)  SCHED_BATCH can be used only at static
       priority 0.  This policy is similar to SCHED_OTHER in that it
       schedules the thread according to its dynamic priority (based on
       the nice value).  The difference is that this policy will cause
       the scheduler to always assume that the thread is CPU-intensive.
       Consequently, the scheduler will apply a small scheduling penalty
       with respect to wakeup behavior, so that this thread is mildly
       disfavored in scheduling decisions.

       This policy is useful for workloads that are noninteractive, but
       do not want to lower their nice value, and for workloads that
       want a deterministic scheduling policy without interactivity
       causing extra preemptions (between the workload's tasks).
```

Extra: https://www.kernel.org/doc/html/latest/scheduler/sched-design-CFS.html#scheduling-policies

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

New informations to add on this issue? Should we open a PR? 🤔

**Comment by jvancoillie** [comment]
yes i think there is an issue. 
I just did the test with the following configuration :
```yaml
scheduler_bundle:
  transport:
    dsn: 'doctrine://default?execution_mode=batch'
  tasks:
    foo:
      type: 'command'
      command: 'debug:router'
      priority: -999
    bar:
      type: 'command'
      command: 'debug:container'
      priority: -998
```
I forced low priority to trigger the error quickly.

but with a default `priority` (0) the problem will occur at the thousandth execution of the task 😢 

result in 
<img width="846" alt="Capture d’écran 2021-05-12 à 12 32 33" src="https://user-images.githubusercontent.com/21243943/117961205-240aa400-b31e-11eb-9b53-d7a5cf3b9a0a.png">


moreover once this exception is raised it is no longer possible to reboot the tasks `The priority is invalid`
