### ISSUE TITLE
FIFO sort

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#93]
Seems that #75 doesn't fix the FIFO sort 😢 

<img width="1217" alt="Capture d’écran 2021-05-03 à 20 55 25" src="https://user-images.githubusercontent.com/21243943/116919699-edfc5e80-ac51-11eb-9b44-be9874913288.png">

```yaml
scheduler_bundle:
  transport:
    dsn: 'doctrine://default?execution_mode=first_in_first_out'
  tasks:
    foo:
      type: 'command'
      command: 'app:foo'
      description: 'foo placeholder task'
      output: true
      single_run: true
    bar:
      type: 'command'
      command: 'app:bar'
      description: 'foo placeholder task'
      output: true
      single_run: true
```

expected `foo` then `bar` right ?
